// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTest.Models;

namespace WebTest.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20211019152648_u")]
    partial class u
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebTest.Models.Phone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhoneLinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneLinkId");

                    b.ToTable("phone");
                });

            modelBuilder.Entity("WebTest.Models.PhoneLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("phonelink");
                });

            modelBuilder.Entity("WebTest.Models.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date1")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PhoneLinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneLinkId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("WebTest.Models.Phone", b =>
                {
                    b.HasOne("WebTest.Models.PhoneLink", null)
                        .WithMany("IDPhone")
                        .HasForeignKey("PhoneLinkId");
                });

            modelBuilder.Entity("WebTest.Models.Users", b =>
                {
                    b.HasOne("WebTest.Models.PhoneLink", null)
                        .WithMany("IDUsers")
                        .HasForeignKey("PhoneLinkId");
                });

            modelBuilder.Entity("WebTest.Models.PhoneLink", b =>
                {
                    b.Navigation("IDPhone");

                    b.Navigation("IDUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
